<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="moniarm" params="parent prefix *origin">

  <!-- Constants for robot dimensions -->
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="0.01" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.01" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.01" /> <!-- Link 3 -->
  <xacro:property name="height3" value="0.01" /> <!-- Link 4 -->
  <xacro:property name="height3" value="0.01" /> <!-- Link 5 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Base Link -->
  <link name="base_link">
      <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
              <mesh filename="package://moniarm_description/meshes/base.stl" scale="0.005 0.005 0.005"/>
          </geometry>
      </collision>
      <visual>
          <origin xyz="0 0 0" rpy="1.5708 0 0"/>
          <geometry>
              <mesh filename="package://moniarm_description/meshes/base.stl" scale="0.005 0.005 0.005"/>
          </geometry>
          <material name="grey"/>
      </visual>
      <inertial>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <mass value="1"/>
          <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      </inertial>
  </link>

  <!-- Joint 1, motor0 -->
  <joint name="${prefix}joint1" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}link1"/>
    <origin xyz="0 0 ${height1}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>
  
  <!-- Link 1-->
  <link name="${prefix}link1">
    <collision>
				<origin rpy="0 0 0" xyz="0 0 0" />
				<geometry>
        <box size="${width} ${width} ${height1}"/>
      </geometry>
			</collision>

    <visual>
      <origin xyz="0.06 -0.12 0.17" rpy="0 0 -1.5708"/>
      <geometry>
					<mesh filename="package://moniarm_description/meshes/link1.stl" scale="0.005 0.005 0.005" />
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
        iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
        izz="${mass / 12.0 * (width*width + width*width)}"/>
      </inertial>
    </link>

    <!-- Joint 2, motor1 -->
    <joint name="${prefix}joint2" type="continuous">
      <parent link="${prefix}link1"/>
      <child link="${prefix}link2"/>
      <origin xyz="0 0.01 ${height2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.7"/>
    </joint>

    <!-- Link 2-->
    <link name="${prefix}link2">
      <collision>
        <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
        <geometry>
          <box size="${width} ${width} ${height2}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="-0.02 -0.1 -0.02" rpy="1.2 -0.1 0"/>
        <geometry>
					<mesh filename="package://moniarm_description/meshes/link2.stl" scale="0.005 0.005 0.005" />
        </geometry>
        <material name="white"/>
      </visual>

      <inertial>
        <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia
          ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
          iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
          izz="${mass / 12.0 * (width*width + width*width)}"/>
        </inertial>
      </link>

      <!-- Joint 3, motor2 -->
      <joint name="${prefix}joint3" type="continuous">
        <parent link="${prefix}link2"/>
        <child link="${prefix}link3"/>
        <origin xyz="0 0.01 ${height2}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <dynamics damping="0.7"/>
      </joint>

      <!-- Link 3 -->
      <link name="${prefix}link3">
        <collision>
          <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
          <geometry>
            <box size="${width} ${width} ${height2}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="-0.02 -0.1 0.0" rpy="1.2 0.3 0"/>
          <geometry>
            <mesh filename="package://moniarm_description/meshes/link3.stl" scale="0.005 0.005 0.005" />
          </geometry>
          <material name="green"/>
        </visual>

        <inertial>
          <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
          <mass value="${mass}"/>
          <inertia
            ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
            iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
            izz="${mass / 12.0 * (width*width + width*width)}"/>
          </inertial>
        </link>

        <!-- Joint 4, motor3 -->
        <joint name="${prefix}joint4" type="continuous">
          <origin xyz="0 0 0.5" rpy="0 0 0" />
          <parent link="${prefix}link3"/>
          <child link="${prefix}link4" />
        </joint>

          <!-- Link 4, motor+link+pump -->
        <link name="${prefix}link4">
        <collision>
          <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
          <geometry>
            <box size="${width} ${width} ${height2}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
            <mesh filename="package://moniarm_description/meshes/link4.stl" scale="0.005 0.005 0.005" />
          </geometry>
          <material name="green"/>
        </visual>

        <inertial>
          <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
          <mass value="${mass}"/>
          <inertia
            ixx="${mass / 12.0 * (width*width + height3*height3)}" ixy="0.0" ixz="0.0"
            iyy="${mass / 12.0 * (height3*height3 + width*width)}" iyz="0.0"
            izz="${mass / 12.0 * (width*width + width*width)}"/>
          </inertial>
        </link>

  </xacro:macro>

</robot>
