/* autogenerated by Processing revision 1293 on 2024-04-13 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.serial.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class hGuideCapture extends PApplet {


PrintWriter output;
Serial COMPort;  // Create object from Serial class

public void setup() 
{
  String portName;
  
  if (args != null) {
    portName = args[0];
  } else {
    portName = "/dev/ttyUSB0";
  }
  
  /* size commented out by preprocessor */;
  noStroke();
  background(0);
  frameRate(5);

  COMPort = new Serial(this, portName, 115200);
  output = createWriter("/home/jetson/ros2_ws/src/moniarm/moniarm_control/moniarm_control/automove.txt"); 
  
  textSize(26); 
  textAlign(CENTER);
  text("press p or space to capture",width/2,60);
  text("Ctrl-C to quit",width/2,100);
}

public void keyPressed() {
  COMPort.write(key);
  if (key == 0x03) {
    text("Bye Bye...",width/2,200);
    output.flush(); // Writes the remaining data to the file
    output.close(); // Finishes the file
    exit(); // Stops the program
  }
}

public void draw() 
{
  if (COMPort.available() > 0) {  // If data is available,
    String read = COMPort.readString();  // read and store it to string read
    output.print(read);
    print(read);
  }
}


  public void settings() { size(400, 400); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "hGuideCapture" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
