#____________________________________________________________________________________________
# get_status()  
#____________________________________________________________________________________________
# This service returns the current moniarm status

---
int8    status
bool    success 

