#____________________________________________________________________________________________
# Init()
#____________________________________________________________________________________________
# This service sets motor operation mode
int8    motor_mode
---
bool    success
