#____________________________________________________________________________________________
# Init()
#____________________________________________________________________________________________
# This service initialize motors
int8    init_mode
---
bool    success
