#____________________________________________________________________________________________
# Init()  
#____________________________________________________________________________________________
# This service returns the current moniarm status
int8    init_mode
---

bool    success 

