#____________________________________________________________________________________________
# Play buzzer song
#____________________________________________________________________________________________
# This service play short song on daughter-MCU
int8    index
---
bool    success
