#____________________________________________________________________________________________
# Play OLED short animation
#____________________________________________________________________________________________
# This service starts OLED animation on daughter-MCU
int8    index
---
bool    success
