#____________________________________________________________________________________________
# Set LED on/off
#____________________________________________________________________________________________
# This service turn on/off on daughter-MCU
int8    index
---
bool    success
